# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxViewModel' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxViewModel
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'Moya/RxSwift'
  pod 'RxOptional'

end
